### ISSUE TITLE
Ajouter des notes sur une période de pointage

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/gta-manager#12]
L'utilisateur du manager doit pouvoir ajouter une note sur une période de pointage. Cette note prend la forme un commentaire libre. Deux type de notes :

- Note public (par défaut) : elle est accessible par le personnel
- Note interne (case à cocher) : elle n'est disponible que dans GTA Manager

Lorsque le manager modifie une période de pointage, il lui est proposé automatiquement d'ajouter une note.

Les notes s'ajoutent dans les notifications à envoyer au personnel.

**Comment by TigrouForMatic** [comment]
AF : Ajouter les notifications
