### ISSUE TITLE
Intégrer la validation de GtaAbsence

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/gta-manager#20]
Lorsque la période de pointage intègre une absence, la validation ou le refus doit remonter au niveau de la GtaAbsence.

**Comment by Guillaume35** [comment]
La requête suivante devra être modifiée :

/api/structureTempsDeclaration/GET/listDeclarations?dd=2023-02-20&df=2023-02-26&group_by_personnel=true

| Paramètre | Type | Description |
| ----- | ----- | ----- |
| **`dd`** | `String` _Obligatoire_ | Date de début de recherche |
| **`df`** | `String` _Obligatoire_ | Date de fin de recherche |
| **`group_by_personnel`** | `Bool` `True` _obligatoire_ | Les enregistrements sont regroupés par personnel |
| **`include_absence`** | `Bool` `True` _obligatoire_ | Le GtaAbsence sont retournées lorsqu'elles existes |

L'attribut **`include_absence`** ajoute une clé `gta_absence` dans le retour comportant un objet GtaAbsence :

```
- personnels
- - [0]
- - - gta_periodes
- - - - [0]
- - - - - gta_absence
```

**Comment by Guillaume35** [comment]
Lire les specs : 
![Application GTA Manager (1)](https://user-images.githubusercontent.com/945411/218062591-07af5ff2-6e94-4b68-89a6-b4da2d13bbdf.png)

https://docs.google.com/document/d/1WVViuU2t58nKh91K8l2nGmWIu0AbEUNJgzgzjkOb_3M/edit#heading=h.9pzbs2uqbucr

**Comment by TigrouForMatic** [comment]
AF : Modifier les valeurs de gta_periodes à gta_absence
